# Generated by Django 4.1.2 on 2022-10-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woman', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woman',
            options={'verbose_name': 'WXoman', 'verbose_name_plural': 'WXomen'},
        ),
        migrations.AlterModelTable(
            name='woman',
            table='women',
        ),
    ]
