# Generated by Django 4.1.2 on 2022-10-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woman', '0002_alter_woman_options_alter_woman_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woman',
            options={'verbose_name': 'Woman', 'verbose_name_plural': 'Women'},
        ),
    ]
